-- MySQL Script generated by MySQL Workbench
-- Tue Dec 27 15:09:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProgettoISPW
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProgettoISPW` ;

-- -----------------------------------------------------
-- Schema ProgettoISPW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProgettoISPW` DEFAULT CHARACTER SET utf8 ;
USE `ProgettoISPW` ;

-- -----------------------------------------------------
-- Table `ProgettoISPW`.`MotivationalPhrase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoISPW`.`MotivationalPhrase` ;

CREATE TABLE IF NOT EXISTS `ProgettoISPW`.`MotivationalPhrase` (
  `idPhrase` INT NOT NULL AUTO_INCREMENT,
  `Phrase` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idPhrase`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS MoteeveUser;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'MoteeveUser' IDENTIFIED BY 'Moteeve';

GRANT ALL ON `ProgettoISPW`.* TO 'MoteeveUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
